feat:reports refactored code to calculate counts
cal-itp/reports pull request #54
Opened 2021-12-06 16:55 UTC by Nkdiaz

Updated code to remove unused code and to have calculated counts for better ease to calculate total counts of validation notices per date in monthly GTFS Reports

2021-12-08 17:43 UTC, machow commented
@Nkdiaz can you paste the before and after screenshots we discussed?

2021-12-08 17:46 UTC, Nkdiaz commented
Reports generated now include a count for validation errors and the report tables now display a count with the updated row structure. I am attaching some before and after screenshots. It is worth mentioning that for this date, there is only one  date and that impacts the arrangement of the files/fields existing table. 
![validation-errors-before missing date](https://user-imag
![Validation errors-after-missing date](https://user-images.githubusercontent.com/32888103/145257428-5f749373-bfd8-4e0c-9ecb-2271f4d0085b.png)
es.githubusercontent.com/32888103/145257417-93db27e4-3b84-48eb-b4fc-08973bef7673.png)

2021-12-08 18:38 UTC, machow commented
Thanks! I'm noticing there's an issue with `views.gtfs_schedule_fact_daily_feed_files` causing it not to show a column for July 6th. It looks like we need to also partition on `T1.name` on this line: https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/gtfs_schedule_fact_daily_feed_files.sql#L43

Let me sanity check quickly to make sure that's the issue and open a PR. Then, when we regenerate reports it should resolve.

2021-12-09 08:35 UTC, evansiroky requested changes
This is all pretty awesome and outputting almost exactly what is expected (aside from that decimal display of the validation count). As noted in a comment, raising a `ValueError` is crashing on a particular feed. 

I have made another PR with some code that at least gets things working that I propose to merge into this branch that gets this working. See https://github.com/cal-itp/reports/pull/59.

2021-12-09 15:25 UTC, machow commented
@evansiroky here is a PR that should fix the file counts missing on certain days (those where our extractor failed). https://github.com/cal-itp/data-infra/pull/842

2021-12-13 14:23 UTC, machow commented on reports/report.ipynb
> +    "        raise ValueError(\"table contained more than 1 row\")\n",
ah, thanks--I think it uses the agency.txt table to connect back to a specific feed_info file as a means of distinguishing the feeds it aggregates :/

2021-12-13 14:24 UTC, machow approved these changes

2021-12-13 16:22 UTC, machow commented
Punted my comments about file checks into a issue, so if useful, we can merge these in and work any useful next steps there: https://github.com/cal-itp/reports/issues/62

2021-12-13 18:09 UTC, evansiroky commented
Thanks for isolating #62. As noted in that issue, let's just hide the columns for now.

However, it would still be good to get the validation errors using the fact tables as mentioned in https://github.com/cal-itp/reports/issues/63.

2021-12-13 18:51 UTC, evansiroky approved these changes

2021-12-13 18:51 UTC, merged